### ISSUE TITLE
Implement in-app feedback form

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#1075]
This meta-issue is about adding an in-app feedback form. Together with the user message, we want to send more:
- platform version
- app version
- logs (a few hundred lines)
- etc

The sub-tasks are probably:
- [x] UI/UX (definition and implementation)
- [x] Collect data and send data to the guardian-webiste
- [x] Store the data in the DB
- [x] Remove the non-encrypted log files and replace them with encrypted files or memory-only logs.

**Comment by jess-cook03** [comment]
Duplicate of #909 -- perhaps we can consolidate?

**Comment by bakulf** [comment]
@jess-cook03 you are right. Let's "reuse" this issue for the code implementation of the feature and the #909 for the UX/UI implementation. Would it work for you?

**Comment by bakulf** [comment]
The non-encrypted log files can be done in a separate step. This feature is completed.

**Comment by ValentinaPC** [comment]
Verified this across platforms, with the last VPN 2.4 builds and checked if all feedback is recorded using https://stage-vpn.guardian.nonprod.cloudops.mozgcp.net/vpn/feedback. Issues found on the way were logged separately.
Marking this as verified.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Nma-Sie-Anyene Davenport The reviewing part for this feature - “If users provide positive In-App feedback (2.4 feature), we will invite them to leave a review for Mozilla VPN in the appropriate app store.”- was pushed to v2.5. But while checking it on VPN 2.5 (16293690), we are still not redirected to the Play Store to be able to provide a review.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

This is not finalized, as https://github.com/mozilla-mobile/mozilla-vpn-client/issues/1294 ( https://github.com/mozilla-mobile/mozilla-vpn-client/issues/1294|smart-link ) can only be checked after a signed build is available in Store. Not sure how would be checked for iOS.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this as fixed on the last VPN 2.5.0 builds on both Android and iOS platforms. (2.202109131634 and 16313840). If the user selects the “Excellent“ option in the feedback form, he is asked to leave a review in Store. After clicking the “Leave review“ option, user is redirected to the Store.
