### ISSUE TITLE
Complete the captive-portal implementation

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#824]
The current plan is to complete the following tasks:

- [x] Android captive portal implementation
- [x] Consider disabling captive-portal by default - See #796
- [x] testing
- [ ] Better UX/UI/Messaging - See #919 - #729
- [x] Captive-portal detection in IPv6 - See #593

**Comment by bakulf** [comment]
Let's move this issue to 2.4 because we are happy with the current captive-portal implementation for v2.3. We can do more in 2.4

**Comment by bakulf** [comment]
We can finally close this issue.
