### ISSUE TITLE
In-app Surveys

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#970]
This is a meta issue to implement in-app surveys. It's composed of the following sub-issues:

- [x] Implement the survey logic (#763)
- [x] Implement the UI component
- [x] Define the survey URLs and when we should trigger them
- [x] Expose the URLs through the guardian-website
- [x] Release the feature

**Comment by ValentinaPC** [comment]
Verified this across platforms on the last VPN 2.3.0 build.
The "Take Survey" banner is displayed in app. Layout looks good.
Except that the Surveys (URLs) are not yet visible - @bakulf any idea when they will be?
