### ISSUE TITLE
Telemetry/Glean implementation

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#972]
- [x] Implement Glean Telemetry #765
- [x] Implement the UI to disable/enable telemetry (#971)
- [x] Define the metrics.yaml
- [x] Data-Review process of the metrics.yaml
